package br.ufscar.pooa.cinema_api.infrastructure.persistence_framework.database;


import br.ufscar.pooa.cinema_api.infrastructure.persistence_framework.annotation.PFColumn;
import br.ufscar.pooa.cinema_api.infrastructure.persistence_framework.annotation.PFId;

import java.lang.reflect.Field;
import java.util.List;
import java.util.stream.Collectors;

public class DDLGenerator {

    public String generateCreateTableSQL(String tableName, List<Field> columns) {
        String columnDefinitions = columns.stream()
                .map(this::getColumnDefinition)
                .collect(Collectors.joining(",\n    "));

        return String.format("""
                CREATE TABLE IF NOT EXISTS %s (
                    %s
                );
                """, tableName, columnDefinitions);
    }

    private String getColumnDefinition(Field field) {
        PFColumn PFColumn = field.getAnnotation(PFColumn.class);

        String columnName = PFColumn.name();
        String dataType = PostgreSQLTypeMapper.getPostgreSQLType(field);

        columnName = columnName.concat(" ").concat(dataType);

        if(field.isAnnotationPresent(PFId.class)){
            return columnName.concat(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        }

        return columnName;
    }

}

